<?php
$z[0]=Array("field","",254,273);
$z[0][4]['name']="title";
$z[1]=Array("global","",274,300);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",341,363);
$z[2][4]['name']="keywords";
$z[3]=Array("field","",403,454);
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("include","",1575,1610);
$z[4][4]['filename']="head.htm";
$z[5]=Array("include","",1667,1702);
$z[5][4]['filename']="left.htm";
$z[6]=Array("include","",1817,1857);
$z[6][4]['filename']="right_nav.htm";
$z[7]=Array("productimagelist","\r\n              <li>\r\n                <table width='680' border='0' cellspacing='0' cellpadding='0'>\r\n                  <tr>\r\n                    <td height='500' align='center' valign='middle'><img src=\"[field:imgsrc/]\" onload='AutoResizeImage(680,500,this)'  /></td>\r\n                  </tr>\r\n                </table>\r\n              </li>\r\n              ",2239,2642);
$z[8]=Array("productimagelist","\r\n              <li><i class='arr2'></i><img src=\"[field:imgsrc/]\"/></li>\r\n              ",2770,2906);
$z[9]=Array("field","",3079,3097);
$z[9][4]['name']="body";
$z[10]=Array("prenext","",3303,3328);
$z[10][4]['get']="pre";
$z[11]=Array("prenext","",3354,3380);
$z[11][4]['get']="next";
$z[12]=Array("include","",3620,3657);
$z[12][4]['filename']="footer.htm";

?>