<?php
$z[0]=Array("channel","\r\n              <li class=\"menu_ii\"><a href='[field:typeurl/]' [field:rel/]>[field:typename/]</a></li>\r\n              ",574,860);
$z[0][4]['type']="top";
$z[0][4]['row']="5";
$z[0][4]['currentstyle']="<li class='hover menu_ii'><a href='~typelink~' ~rel~>~typename~</a></li>";
$z[1]=Array("global","",1013,1039);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("arclist","\r\n    <div><img src=\"[field:litpic/]\"  alt=\"[field:fulltitle/]\"></div>\r\n    ",1375,1514);
$z[2][4]['row']="10";
$z[2][4]['orderby']="id";
$z[2][4]['typeid']="17";
$z[3]=Array("global","",1642,1668);
$z[3][4]['name']="cfg_webname";

?>