<?php
$z[0]=Array("channel","\r\n              <li class=\"menu_ii\"><a href='[field:typeurl/]' [field:rel/]>[field:typename/]</a></li>\r\n              ",588,874);
$z[0][4]['type']="top";
$z[0][4]['row']="5";
$z[0][4]['currentstyle']="<li class='hover menu_ii'><a href='~typelink~' ~rel~>~typename~</a></li>";
$z[1]=Array("global","",1027,1053);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("arclist","\r\n    <div><img src=\"[field:picname/]\"  alt=\"[field:fulltitle/]\"></div>\r\n    ",1389,1516);
$z[2][4]['row']="10";
$z[2][4]['typeid']="17";

?>