<?php
$z[0]=Array("type","<a href=\"[field:typelink/]\">+ 灯具 Lamp</a>",46,125);
$z[0][4]['typeid']="3";
$z[1]=Array("type","<a href=\"[field:typelink/]\">+ 窗帘 Curiain</a>",172,254);
$z[1][4]['typeid']="4";
$z[2]=Array("type","<a href=\"[field:typelink/]\">+ 地毯 Carpet</a>",301,382);
$z[2][4]['typeid']="5";
$z[3]=Array("type","<a href=\"[field:typelink/]\">+ 家具 Furniture</a>",429,513);
$z[3][4]['typeid']="6";
$z[4]=Array("type","<a href=\"[field:typelink/]\">+ 全案  Full Service</a>",560,648);
$z[4][4]['typeid']="7";
$z[5]=Array("type","<a href=\"[field:typelink/]\">+ 其他 Other</a>",695,775);
$z[5][4]['typeid']="8";

?>