<?php
$z[0]=Array("global","",236,264);
$z[0][4]['name']="cfg_soft_lang";
$z[1]=Array("field","",277,296);
$z[1][4]['name']="title";
$z[2]=Array("global","",297,323);
$z[2][4]['name']="cfg_webname";
$z[3]=Array("field","",364,393);
$z[3][4]['name']="keywords";
$z[4]=Array("field","",433,491);
$z[4][4]['name']="description";
$z[4][4]['function']="html2text(@me)";
$z[5]=Array("include","",621,656);
$z[5][4]['filename']="head.htm";
$z[6]=Array("include","",713,748);
$z[6][4]['filename']="left.htm";
$z[7]=Array("include","",832,872);
$z[7][4]['filename']="right_nav.htm";
$z[8]=Array("channel"," <a href='[field:typeurl/]'>[field:typename/]</a> ",911,1071);
$z[8][4]['type']="son";
$z[8][4]['currentstyle']="<a href='~typelink~' class='thisclass2'>~typename~</a>";
$z[9]=Array("list","\r\n          <li><a href=\"[field:arcurl/]\"><img src=\"[field:picname/]\" alt=\"[field:title/]\"/></a>\r\n            <p class=\"ny_news_bt\"><a href=\"[field:arcurl/]\" >[field:title/]</a></p>\r\n            <p>[field:description function='cn_substr(@me,400)'/]......</p>\r\n            <p class=\"ny_news_more\"><a href=\"[field:arcurl/]\">阅读全文 ></a></p>\r\n            </td>\r\n          </li>\r\n          ",1208,1651);
$z[9][4]['pagesize']="15";
$z[9][4]['titlelen']="90";
$z[10]=Array("pagelist","",1790,1868);
$z[10][4]['listitem']="info,index,end,pre,next,pageno,option";
$z[10][4]['listsize']="5";
$z[11]=Array("include","",1956,1993);
$z[11][4]['filename']="footer.htm";

?>